prooph_service_bus:
  event_buses:
    todo_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'
        routes:
          'App\Domain\Category\Events\CategoryWasCreated':
            - '@App\Infrastructure\Category\Projection\CategoryReadModel'
